#!/bin/bash
# Main file contains general logic of the script and utility functions

# copyToWithName local_file_name remote_host_name
# Copy local file to remote host
function copyToWithName()
{
scp ./$2 $1:/home/$USER/$2
}

# getAllARPResults
# Get ARP results from remote hosts
function getAllARPResults()
{
for host in April December March February
do	
  scp $host:/home/$USER/ARPResults* ./ARPResults_from_$host
  cat ARPResults_from_$host >>ARPResults
done
}

# getResultsFromRemoteHosts
# get ARP and Ping results from remote hosts
function getResultsFromRemoteHosts()
{
scp April:/home/$USER/PingPackets .
getAllARPResults
}

# Start from April.net16 and ping the rest of the network
ssh -Y April "bash -s" < remote_ping

# Get ARPResults and PingPackets results from April.net16, November.net17, May.net18 and October.net19
getResultsFromRemoteHosts

# Generate IP to Ethernet mapping from all ARP dump results and append to StationsUp
#for subnet in 16 17 18 19
#do

cat ARPResults | awk '{print $2,$4;}' | sort -t . -k 1,1n -k 2,2n -k 3,3n -k 4,4n | sed 's/(/ip address /'| sed 's/) <incomplete>/ is not available. /'| sed 's/) [0-9]/ has Ethernet address 0/'>StationsUp
#done